### ISSUE TITLE
关于计算状态转移噪声的两种方法的出处

### ISSUE THREAD

**Issue by xy-23** [SnocrashWang/WMJAimer#1]
两种方法分别为Continuous White Noise Model和Piecewise White Noise Model. 具体内容在[这篇文章](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb)的子标题Design of the Process Noise Matrix下面，出处应该就在文末的参考链接中。

**Comment by SnocrashWang** [comment]
> 两种方法分别为Continuous White Noise Model和Piecewise White Noise Model. 具体内容在[这篇文章](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/07-Kalman-Filter-Math.ipynb)的子标题Design of the Process Noise Matrix下面，出处应该就在文末的参考链接中。

感谢你的补充！
